# Generated by Django 4.2 on 2026-01-29 07:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mother',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Mother's first name", max_length=100)),
                ('last_name', models.CharField(help_text="Mother's last name", max_length=100)),
                ('date_of_birth', models.DateField(help_text="Mother's date of birth (for age calculation)")),
                ('national_id', models.CharField(blank=True, help_text='National ID number (if available)', max_length=20, null=True, unique=True)),
                ('phone_number', models.CharField(help_text='Primary phone number for SMS reminders (REQUIRED)', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone format: '+254712345678'", regex='^\\+?254?\\d{9,12}$')])),
                ('alternate_phone', models.CharField(blank=True, help_text='Alternative contact number', max_length=15)),
                ('county', models.CharField(help_text='County of residence', max_length=100)),
                ('sub_county', models.CharField(help_text='Sub-county of residence', max_length=100)),
                ('ward', models.CharField(help_text='Ward of residence', max_length=100)),
                ('village', models.CharField(blank=True, help_text='Village/Estate (optional)', max_length=100)),
                ('registration_date', models.DateField(auto_now_add=True, help_text='Date when mother was registered in the system')),
                ('next_of_kin_name', models.CharField(blank=True, help_text='Next of kin full name', max_length=200)),
                ('next_of_kin_phone', models.CharField(blank=True, help_text='Next of kin phone number', max_length=15)),
                ('next_of_kin_relationship', models.CharField(blank=True, help_text='Relationship to mother (e.g., Husband, Sister, Mother)', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text="Is this mother's record active in the system?")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(help_text='Health facility where mother is registered', on_delete=django.db.models.deletion.PROTECT, related_name='mothers', to='users.facility')),
                ('registered_by', models.ForeignKey(help_text='Nurse/CHV who registered this mother', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_mothers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mother',
                'verbose_name_plural': 'Mothers',
                'db_table': 'mothers',
                'ordering': ['-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='Pregnancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnancy_number', models.IntegerField(help_text='Gravida - Total number of pregnancies including current (1, 2, 3, etc.)')),
                ('lmp', models.DateField(help_text='First day of last menstrual period (used to calculate EDD)', verbose_name='Last Menstrual Period')),
                ('edd', models.DateField(editable=False, help_text='AUTO-CALCULATED: LMP + 280 days (40 weeks)', verbose_name='Estimated Due Date')),
                ('gestational_age_weeks', models.IntegerField(default=0, editable=False, help_text='AUTO-CALCULATED: Current weeks of pregnancy')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], default='LOW', help_text='Risk level based on maternal factors', max_length=20)),
                ('risk_factors', models.TextField(blank=True, help_text='Details: High BP, diabetes, previous C-section, age >35, etc.')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DELIVERED', 'Delivered'), ('MISCARRIAGE', 'Miscarriage'), ('STILLBIRTH', 'Stillbirth'), ('TRANSFERRED', 'Transferred to Another Facility')], default='ACTIVE', help_text='Current status of this pregnancy', max_length=20)),
                ('registration_date', models.DateField(auto_now_add=True, help_text='Date when pregnancy was registered')),
                ('parity', models.IntegerField(default=0, help_text='Number of previous deliveries (P0, P1, P2, etc.)')),
                ('previous_csection', models.BooleanField(default=False, help_text='Has mother had a C-section before?')),
                ('previous_complications', models.TextField(blank=True, help_text='Details of any previous pregnancy/delivery complications')),
                ('notes', models.TextField(blank=True, help_text='Additional clinical notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(help_text='Facility where pregnancy is being managed', on_delete=django.db.models.deletion.PROTECT, related_name='pregnancies', to='users.facility')),
                ('mother', models.ForeignKey(help_text='Mother for this pregnancy', on_delete=django.db.models.deletion.CASCADE, related_name='pregnancies', to='mothers.mother')),
                ('registered_by', models.ForeignKey(help_text='Nurse/CHV who registered this pregnancy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_pregnancies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pregnancy',
                'verbose_name_plural': 'Pregnancies',
                'db_table': 'pregnancies',
                'ordering': ['-registration_date'],
            },
        ),
        migrations.AddIndex(
            model_name='pregnancy',
            index=models.Index(fields=['facility', 'status'], name='pregnancies_facilit_bb4fae_idx'),
        ),
        migrations.AddIndex(
            model_name='pregnancy',
            index=models.Index(fields=['edd'], name='pregnancies_edd_c5cbb2_idx'),
        ),
        migrations.AddIndex(
            model_name='pregnancy',
            index=models.Index(fields=['risk_level', 'status'], name='pregnancies_risk_le_f9b4c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pregnancy',
            unique_together={('mother', 'pregnancy_number')},
        ),
        migrations.AddIndex(
            model_name='mother',
            index=models.Index(fields=['facility', 'is_active'], name='mothers_facilit_7a6391_idx'),
        ),
        migrations.AddIndex(
            model_name='mother',
            index=models.Index(fields=['phone_number'], name='mothers_phone_n_337725_idx'),
        ),
        migrations.AddIndex(
            model_name='mother',
            index=models.Index(fields=['county', 'sub_county'], name='mothers_county_93a8b5_idx'),
        ),
    ]
