# Generated by Django 4.2 on 2026-02-02 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mothers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(help_text='Date of delivery')),
                ('delivery_time', models.TimeField(help_text='Time of delivery (24-hour format)')),
                ('delivery_type', models.CharField(choices=[('SVD', 'Spontaneous Vaginal Delivery (Normal)'), ('ASSISTED', 'Assisted Vaginal Delivery (Vacuum/Forceps)'), ('CSECTION', 'Caesarean Section'), ('BREECH', 'Breech Delivery')], help_text='Type/mode of delivery', max_length=20)),
                ('delivery_outcome', models.CharField(choices=[('LIVE', 'Live Birth'), ('STILLBIRTH', 'Stillbirth'), ('NEONATAL_DEATH', 'Neonatal Death (within 24 hours)')], help_text='Outcome of delivery', max_length=20)),
                ('number_of_babies', models.IntegerField(default=1, help_text='Number of babies born (1=singleton, 2=twins, 3=triplets)')),
                ('mother_condition', models.CharField(blank=True, help_text="Mother's condition after delivery (stable, critical, etc.)", max_length=100)),
                ('complications', models.TextField(blank=True, help_text='Any complications during delivery (hemorrhage, pre-eclampsia, etc.)')),
                ('blood_loss_ml', models.IntegerField(blank=True, help_text='Estimated blood loss in milliliters', null=True)),
                ('placenta_complete', models.BooleanField(default=True, help_text='Was placenta delivered completely?')),
                ('placenta_weight_grams', models.IntegerField(blank=True, help_text='Weight of placenta in grams', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional clinical notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attended_by', models.ForeignKey(blank=True, help_text='Healthcare provider who attended delivery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attended_deliveries', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(help_text='Facility where delivery occurred', on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='users.facility')),
                ('pregnancy', models.OneToOneField(help_text='Pregnancy that ended in this delivery', on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='mothers.pregnancy')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
                'db_table': 'deliveries',
                'ordering': ['-delivery_date', '-delivery_time'],
            },
        ),
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, help_text="Baby's first name (can be added later)", max_length=100)),
                ('middle_name', models.CharField(blank=True, help_text="Baby's middle name (optional)", max_length=100)),
                ('last_name', models.CharField(blank=True, help_text="Baby's last name (usually same as mother)", max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], help_text="Baby's gender", max_length=1)),
                ('birth_weight_grams', models.IntegerField(help_text='Birth weight in grams (e.g., 3200 for 3.2kg)')),
                ('birth_length_cm', models.DecimalField(blank=True, decimal_places=2, help_text='Birth length in centimeters', max_digits=5, null=True)),
                ('head_circumference_cm', models.DecimalField(blank=True, decimal_places=2, help_text='Head circumference in centimeters', max_digits=5, null=True)),
                ('apgar_score_1min', models.IntegerField(blank=True, help_text='APGAR score at 1 minute (0-10)', null=True)),
                ('apgar_score_5min', models.IntegerField(blank=True, help_text='APGAR score at 5 minutes (0-10)', null=True)),
                ('birth_order', models.IntegerField(default=1, help_text='Birth order for multiple births (1st, 2nd, 3rd)')),
                ('health_condition', models.CharField(blank=True, help_text="Baby's health condition at birth (healthy, needs monitoring, etc.)", max_length=100)),
                ('complications', models.TextField(blank=True, help_text='Any birth complications or health issues')),
                ('required_resuscitation', models.BooleanField(default=False, help_text='Did baby require resuscitation?')),
                ('birth_notification_number', models.CharField(blank=True, help_text='Birth notification number (if registered)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery', models.ForeignKey(help_text='Delivery event when baby was born', on_delete=django.db.models.deletion.CASCADE, related_name='babies', to='delivery.delivery')),
                ('facility', models.ForeignKey(help_text='Facility where baby was born', on_delete=django.db.models.deletion.PROTECT, related_name='babies', to='users.facility')),
                ('mother', models.ForeignKey(help_text='Mother of this baby', on_delete=django.db.models.deletion.CASCADE, related_name='babies', to='mothers.mother')),
                ('registered_by', models.ForeignKey(blank=True, help_text='Staff who registered the baby', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_babies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Baby',
                'verbose_name_plural': 'Babies',
                'db_table': 'babies',
                'ordering': ['-delivery__delivery_date', 'birth_order'],
            },
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['facility', 'delivery_date'], name='deliveries_facilit_39320c_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['delivery_outcome'], name='deliveries_deliver_ddbd14_idx'),
        ),
        migrations.AddIndex(
            model_name='baby',
            index=models.Index(fields=['mother', 'delivery'], name='babies_mother__7b4791_idx'),
        ),
        migrations.AddIndex(
            model_name='baby',
            index=models.Index(fields=['facility'], name='babies_facilit_4c74bc_idx'),
        ),
    ]
