# Generated by Django 4.2 on 2026-02-04 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('immunization', '0001_initial'),
        ('anc', '0001_initial'),
        ('delivery', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mothers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('ANC_UPCOMING', 'ANC Visit Upcoming (3 days before)'), ('ANC_TODAY', 'ANC Visit Today'), ('ANC_MISSED', 'ANC Visit Missed (Follow-up)'), ('VACCINE_UPCOMING', 'Vaccination Upcoming (3 days before)'), ('VACCINE_TODAY', 'Vaccination Today'), ('VACCINE_MISSED', 'Vaccination Missed (Follow-up)'), ('PNC_UPCOMING', 'Postnatal Care Upcoming'), ('DANGER_SIGNS', 'Danger Signs Alert'), ('DELIVERY_APPROACHING', 'Delivery Approaching (2 weeks)'), ('OVERDUE_PREGNANCY', 'Pregnancy Overdue'), ('GENERAL', 'General Reminder')], help_text='Type of reminder this template is for', max_length=30, unique=True)),
                ('name', models.CharField(help_text='Template name for easy identification', max_length=200)),
                ('message_template', models.TextField(help_text="SMS template with placeholders:\n{name} - Mother's name\n{visit_number} - ANC visit number\n{date} - Appointment date\n{time} - Appointment time\n{facility} - Facility name\n{vaccine_name} - Vaccine name\n{baby_name} - Baby's name\n{weeks_pregnant} - Gestational age\n{edd} - Expected due date")),
                ('is_active', models.BooleanField(default=True, help_text='Is this template currently active?')),
                ('days_before', models.IntegerField(default=3, help_text='How many days before appointment to send (0 = same day)')),
                ('send_time', models.TimeField(default='09:00:00', help_text='What time of day to send (24-hour format)')),
                ('description', models.TextField(blank=True, help_text='Internal notes about this template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reminder Template',
                'verbose_name_plural': 'Reminder Templates',
                'db_table': 'reminder_templates',
                'ordering': ['reminder_type'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('LOGIN_FAILED', 'Failed Login Attempt'), ('CREATE', 'Record Created'), ('UPDATE', 'Record Updated'), ('DELETE', 'Record Deleted'), ('VIEW', 'Record Viewed'), ('SMS_SENT', 'SMS Sent'), ('SMS_FAILED', 'SMS Failed'), ('SMS_DELIVERED', 'SMS Delivered'), ('CRON_RUN', 'Cron Job Executed'), ('BULK_UPDATE', 'Bulk Update Performed'), ('EXPORT', 'Data Exported'), ('IMPORT', 'Data Imported'), ('DANGER_SIGN', 'Danger Sign Flagged'), ('MISSED_VISIT', 'Visit Marked as Missed'), ('OVERDUE_PREGNANCY', 'Pregnancy Marked as Overdue')], help_text='Type of action performed', max_length=30)),
                ('log_level', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', help_text='Severity level of this log entry', max_length=20)),
                ('model_name', models.CharField(blank=True, help_text='Name of the model that was affected', max_length=100)),
                ('object_id', models.CharField(blank=True, help_text='ID of the specific record affected', max_length=100)),
                ('description', models.TextField(help_text='Detailed description of what happened')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user (if applicable)', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device information (if applicable)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context data (JSON format)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this action occurred')),
                ('facility', models.ForeignKey(blank=True, help_text='Facility where action occurred (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to='users.facility')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action (null for system actions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Log',
                'verbose_name_plural': 'System Logs',
                'db_table': 'system_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Phone number SMS was sent to', max_length=15)),
                ('reminder_type', models.CharField(choices=[('ANC_UPCOMING', 'ANC Visit Upcoming'), ('ANC_TODAY', 'ANC Visit Today'), ('ANC_MISSED', 'ANC Visit Missed'), ('VACCINE_UPCOMING', 'Vaccination Upcoming'), ('VACCINE_TODAY', 'Vaccination Today'), ('VACCINE_MISSED', 'Vaccination Missed'), ('PNC_UPCOMING', 'Postnatal Care Upcoming'), ('DANGER_SIGNS', 'Danger Signs Alert'), ('DELIVERY_APPROACHING', 'Delivery Approaching'), ('OVERDUE_PREGNANCY', 'Pregnancy Overdue'), ('GENERAL', 'General Reminder')], help_text='Type of reminder', max_length=30)),
                ('message_content', models.TextField(help_text='Actual SMS text that was sent')),
                ('scheduled_datetime', models.DateTimeField(help_text='When system scheduled this SMS to be sent')),
                ('sent_datetime', models.DateTimeField(blank=True, help_text='When SMS was actually sent to gateway', null=True)),
                ('delivered_datetime', models.DateTimeField(blank=True, help_text='When SMS was delivered to phone (if confirmed)', null=True)),
                ('delivery_status', models.CharField(choices=[('PENDING', 'Pending (not sent yet)'), ('SENT', 'Sent to gateway'), ('DELIVERED', 'Delivered to phone'), ('FAILED', 'Failed to send'), ('INVALID_NUMBER', 'Invalid phone number'), ('REJECTED', 'Rejected by gateway')], default='PENDING', help_text='Current status of this SMS', max_length=20)),
                ('gateway_response', models.TextField(blank=True, help_text="Response from SMS gateway (Africa's Talking, etc.)")),
                ('gateway_message_id', models.CharField(blank=True, help_text='Message ID from gateway for tracking', max_length=100)),
                ('retry_count', models.IntegerField(default=0, help_text='Number of times sending was retried')),
                ('max_retries', models.IntegerField(default=3, help_text='Maximum number of retry attempts')),
                ('next_retry_datetime', models.DateTimeField(blank=True, help_text='When to retry if failed', null=True)),
                ('sms_cost', models.DecimalField(blank=True, decimal_places=4, help_text='Cost of this SMS (in KES)', max_digits=6, null=True)),
                ('is_manual', models.BooleanField(default=False, help_text='Was this sent manually or auto-generated?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anc_visit', models.ForeignKey(blank=True, help_text='Related ANC visit (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='anc.ancvisit')),
                ('baby', models.ForeignKey(blank=True, help_text='Related baby (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='delivery.baby')),
                ('facility', models.ForeignKey(help_text='Facility that initiated this reminder', on_delete=django.db.models.deletion.PROTECT, related_name='sent_reminders', to='users.facility')),
                ('immunization', models.ForeignKey(blank=True, help_text='Related immunization (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='immunization.immunizationschedule')),
                ('mother', models.ForeignKey(help_text='Mother who received this SMS', on_delete=django.db.models.deletion.CASCADE, related_name='reminders_received', to='mothers.mother')),
                ('pregnancy', models.ForeignKey(blank=True, help_text='Related pregnancy (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='mothers.pregnancy')),
                ('sent_by', models.ForeignKey(blank=True, help_text='User who triggered this reminder (if manual)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders_sent', to=settings.AUTH_USER_MODEL)),
                ('template_used', models.ForeignKey(blank=True, help_text='Template used to generate this message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_reminders', to='reminders.remindertemplate')),
            ],
            options={
                'verbose_name': 'Sent Reminder',
                'verbose_name_plural': 'Sent Reminders',
                'db_table': 'sent_reminders',
                'ordering': ['-scheduled_datetime'],
            },
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['user', 'timestamp'], name='system_logs_user_id_942324_idx'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['action_type', 'timestamp'], name='system_logs_action__60b2ec_idx'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['model_name', 'object_id'], name='system_logs_model_n_82529a_idx'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['log_level'], name='system_logs_log_lev_897a99_idx'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['facility', 'timestamp'], name='system_logs_facilit_aa19e4_idx'),
        ),
        migrations.AddIndex(
            model_name='sentreminder',
            index=models.Index(fields=['mother', 'reminder_type'], name='sent_remind_mother__87d42c_idx'),
        ),
        migrations.AddIndex(
            model_name='sentreminder',
            index=models.Index(fields=['delivery_status'], name='sent_remind_deliver_cadbcb_idx'),
        ),
        migrations.AddIndex(
            model_name='sentreminder',
            index=models.Index(fields=['scheduled_datetime'], name='sent_remind_schedul_b8501d_idx'),
        ),
        migrations.AddIndex(
            model_name='sentreminder',
            index=models.Index(fields=['facility', 'sent_datetime'], name='sent_remind_facilit_8c6e17_idx'),
        ),
        migrations.AddIndex(
            model_name='sentreminder',
            index=models.Index(fields=['phone_number'], name='sent_remind_phone_n_b20d09_idx'),
        ),
    ]
