# Generated by Django 4.2 on 2026-02-04 06:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentreminder',
            name='scheduled_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When system scheduled this SMS to be sent'),
        ),
    ]
