# Generated by Django 4.2 on 2026-02-02 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Vaccine name (e.g., BCG, OPV 1, Pentavalent 1)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='What this vaccine protects against')),
                ('recommended_age_weeks', models.IntegerField(help_text='Recommended age in weeks when vaccine should be given')),
                ('is_active', models.BooleanField(default=True, help_text='Is this vaccine currently in use?')),
                ('route', models.CharField(blank=True, help_text='Route of administration (oral, IM, SC, ID)', max_length=50)),
                ('site', models.CharField(blank=True, help_text='Site of administration (right thigh, left thigh, etc.)', max_length=50)),
                ('dosage', models.CharField(blank=True, help_text='Dosage (e.g., 0.5ml, 2 drops)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vaccine Type',
                'verbose_name_plural': 'Vaccine Types',
                'db_table': 'vaccine_types',
                'ordering': ['recommended_age_weeks', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ImmunizationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(help_text='Date when vaccine is scheduled (AUTO-CALCULATED)')),
                ('administered', models.BooleanField(default=False, help_text='Has vaccine been given?')),
                ('administration_date', models.DateField(blank=True, help_text='Date when vaccine was actually given', null=True)),
                ('missed', models.BooleanField(default=False, help_text='Was vaccine missed? (more than 4 weeks overdue)')),
                ('batch_number', models.CharField(blank=True, help_text='Vaccine batch/lot number', max_length=50)),
                ('expiry_date', models.DateField(blank=True, help_text='Vaccine expiry date', null=True)),
                ('adverse_event', models.BooleanField(default=False, help_text='Did baby experience any adverse event?')),
                ('adverse_event_details', models.TextField(blank=True, help_text='Details of adverse event (fever, rash, swelling, etc.)')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('administered_by', models.ForeignKey(blank=True, help_text='Healthcare worker who administered vaccine', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_vaccines', to=settings.AUTH_USER_MODEL)),
                ('baby', models.ForeignKey(help_text='Baby this vaccine is scheduled for', on_delete=django.db.models.deletion.CASCADE, related_name='immunization_schedules', to='delivery.baby')),
                ('facility', models.ForeignKey(help_text='Facility where vaccine was/will be given', on_delete=django.db.models.deletion.PROTECT, related_name='immunizations', to='users.facility')),
                ('vaccine', models.ForeignKey(help_text='Type of vaccine', on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='immunization.vaccinetype')),
            ],
            options={
                'verbose_name': 'Immunization Schedule',
                'verbose_name_plural': 'Immunization Schedules',
                'db_table': 'immunization_schedules',
                'ordering': ['baby', 'scheduled_date'],
            },
        ),
        migrations.AddIndex(
            model_name='immunizationschedule',
            index=models.Index(fields=['facility', 'scheduled_date'], name='immunizatio_facilit_c384d3_idx'),
        ),
        migrations.AddIndex(
            model_name='immunizationschedule',
            index=models.Index(fields=['scheduled_date', 'administered'], name='immunizatio_schedul_10806c_idx'),
        ),
        migrations.AddIndex(
            model_name='immunizationschedule',
            index=models.Index(fields=['baby', 'administered'], name='immunizatio_baby_id_74a26d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='immunizationschedule',
            unique_together={('baby', 'vaccine')},
        ),
    ]
