# Generated by Django 4.2 on 2026-01-30 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mothers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ANCVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_number', models.IntegerField(help_text='Contact number (1-8, following Kenya MoH 2022 Guidelines)')),
                ('scheduled_date', models.DateField(help_text='Date when visit is scheduled (AUTO-GENERATED)')),
                ('actual_visit_date', models.DateField(blank=True, help_text='Date when mother actually attended', null=True)),
                ('attended', models.BooleanField(default=False, help_text='Did mother attend this visit?')),
                ('missed', models.BooleanField(default=False, help_text='Visit was missed (marked after 7+ days late)')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text="Mother's weight in kilograms", max_digits=5, null=True)),
                ('blood_pressure', models.CharField(blank=True, help_text='Blood pressure reading (e.g., 120/80)', max_length=20)),
                ('hemoglobin', models.DecimalField(blank=True, decimal_places=1, help_text='Hemoglobin level (g/dL)', max_digits=4, null=True)),
                ('fundal_height', models.IntegerField(blank=True, help_text='Fundal height in centimeters', null=True)),
                ('fetal_heartbeat', models.BooleanField(default=True, help_text='Fetal heartbeat detected?')),
                ('has_danger_signs', models.BooleanField(default=False, help_text='Does mother show any danger signs?')),
                ('danger_signs_notes', models.TextField(blank=True, help_text='Details of danger signs (bleeding, severe headache, blurred vision, etc.)')),
                ('iron_given', models.BooleanField(default=False, help_text='Iron supplement given?')),
                ('folic_acid_given', models.BooleanField(default=False, help_text='Folic acid supplement given?')),
                ('deworming_done', models.BooleanField(default=False, help_text='Deworming medication given?')),
                ('tetanus_vaccine_given', models.BooleanField(default=False, help_text='Tetanus vaccine (TT) given?')),
                ('clinical_notes', models.TextField(blank=True, help_text="Nurse's clinical observations and notes")),
                ('next_visit_date', models.DateField(blank=True, help_text='Recommended date for next visit', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(help_text='Facility where visit occurred', on_delete=django.db.models.deletion.PROTECT, related_name='anc_visits', to='users.facility')),
                ('pregnancy', models.ForeignKey(help_text='Pregnancy this visit belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='anc_visits', to='mothers.pregnancy')),
                ('recorded_by', models.ForeignKey(blank=True, help_text='Nurse/CHV who recorded this visit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_anc_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ANC Visit',
                'verbose_name_plural': 'ANC Visits',
                'db_table': 'anc_visits',
                'ordering': ['pregnancy', 'visit_number'],
            },
        ),
        migrations.AddIndex(
            model_name='ancvisit',
            index=models.Index(fields=['facility', 'scheduled_date'], name='anc_visits_facilit_85e442_idx'),
        ),
        migrations.AddIndex(
            model_name='ancvisit',
            index=models.Index(fields=['scheduled_date', 'attended'], name='anc_visits_schedul_6f3255_idx'),
        ),
        migrations.AddIndex(
            model_name='ancvisit',
            index=models.Index(fields=['pregnancy', 'attended'], name='anc_visits_pregnan_084b5f_idx'),
        ),
        migrations.AddIndex(
            model_name='ancvisit',
            index=models.Index(fields=['has_danger_signs'], name='anc_visits_has_dan_429442_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ancvisit',
            unique_together={('pregnancy', 'visit_number')},
        ),
    ]
