# Generated by Django 4.2 on 2026-01-28 08:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('NURSE', 'Nurse/CHV'), ('MANAGER', 'Facility Manager'), ('MOH', 'MOH Administrator')], help_text="User's role in the system", max_length=20)),
                ('phone_number', models.CharField(help_text="User's mobile number (must be unique)", max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone format: '+254712345678'", regex='^\\+?254?\\d{9,12}$')])),
                ('is_active_user', models.BooleanField(default=True, help_text='Can this user access the system?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Official facility name', max_length=200)),
                ('facility_level', models.CharField(choices=[('LEVEL_1', 'Level 1 - Community Health Services'), ('LEVEL_2', 'Level 2 - Dispensaries and Clinics'), ('LEVEL_3', 'Level 3 - Health Centres and Maternity Homes'), ('LEVEL_4', 'Level 4 - Primary Hospitals (Sub-County)'), ('LEVEL_5', 'Level 5 - Secondary Hospitals (County Referral)'), ('LEVEL_6', 'Level 6 - Tertiary Hospitals (National Referral)')], help_text='Kenya health system level (1-6)', max_length=20)),
                ('mfl_code', models.CharField(blank=True, help_text='Master Facility List Code (if available)', max_length=20)),
                ('county', models.CharField(max_length=100)),
                ('sub_county', models.CharField(max_length=100)),
                ('ward', models.CharField(blank=True, max_length=100)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone format: '+254712345678'", regex='^\\+?254?\\d{9,12}$')])),
                ('alternate_phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True, help_text='Is facility currently operational?')),
                ('is_24_hours', models.BooleanField(default=False, help_text='Does facility operate 24/7?')),
                ('has_maternity_services', models.BooleanField(default=True, help_text='Does facility provide maternal health services?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
                'db_table': 'facilities',
                'ordering': ['county', 'facility_level', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['county', 'sub_county'], name='facilities_county_f2eb46_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['facility_level'], name='facilities_facilit_73c45d_idx'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='facility',
            field=models.ForeignKey(blank=True, help_text='Health facility where user works (optional for MOH admins)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='users.facility'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='users_role_0ace22_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['facility'], name='users_facilit_6a55d8_idx'),
        ),
    ]
